#!/usr/bin/awk

# Simple-minded documentation generator for TCL procedures.
# Outputs MoinMoin formatting. 

# Double ## are discarded. 
# Triple ### are a verbatim block.
# ' proc' are not output.

BEGIN {
    lastblock="";
}

/^###ID/ {
    "env LC_TIME=C date" | getline date;
    print "\nDocumentation autogenerated by {{{autodoc.awk}}} on " date
}

/^# .+ -+$/ {
    $1=""; $NF="";
    print "   " lastblock;
    print "== "  $0 " =="
    lastblock = ""
    next
}

/^# / {
#    print "COMMENT "  $0
    $1="";
    lastblock = lastblock  $0;
}

/^### / {
    sub(/^### /,"");
    print $0;
}


/^proc/ {
#    print "PROC "  $0
    $1=""; $NF="";
    print " * '''" $0 "'''"
    print ""
    print "   " lastblock;
    print ""
    lastblock = ""
}

/^ proc/ {
    lastblock =""
}
