name: Doxygen

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
    - name: Install Doxygen
      run: conda install -c conda-forge --yes doxygen=1.8.17
    - name: Run Doxygen
      run: doxygen Doxyfile